### PR TITLE
Added an ability to specify container for geojson shapes

### PR DESCRIPTION
**Pull request by dcbrwn**
Also made the demo a little bit prettier.

### CODE REVIEW

**Comment by dcbrwn** [comment]
Now it should look like this
image

**Comment by jdomingu** [comment]
Awesome. Really nicely done, and thanks!

**Comment by dcbrwn** [comment]
@jdomingu Thanks for a great lib btw! I've used it to render countries map in this project (but used a bit different geojson):
https://2017.spaceappschallenge.org/challenges/ideate-and-create/1d-2d-3d-go/teams/hala-1/project

**Comment by jdomingu** [comment]
Love your project @dcbrwn . So glad to someone getting real world use out of this 👍

**Pull request merged**
